import React, { useRef } from "react";
import { toPng } from "html-to-image";
import { motion } from "framer-motion";
import { Download, RefreshCw, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useIdea } from "../context/IdeaContext";

const Scorecard = () => {
  const { roastResult, resetRoast } = useIdea();
  const cardRef = useRef(null);

  if (!roastResult) return null;

  // Color logic based on score
  const isTrash = roastResult.score < 50;
  const scoreColor = isTrash ? "text-destructive" : "text-primary";
  const borderColor = isTrash ? "border-destructive/50" : "border-primary/50";

  const downloadImage = async () => {
    if (cardRef.current === null) return;
    try {
      const dataUrl = await toPng(cardRef.current, { cacheBust: true });
      const link = document.createElement("a");
      link.download = "boardroom-verdict.png";
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error("Failed to generate image", err);
    }
  };

  return (
    <div className="w-full max-w-2xl mx-auto">
      {/* THE CAPTURE AREA (This is what gets downloaded) */}
      <div
        ref={cardRef}
        className={`bg-card border-2 ${borderColor} rounded-xl shadow-2xl overflow-hidden relative p-8 md:p-12 text-center`}
      >
        {/* Background Texture/Watermark */}
        <div className="absolute inset-0 opacity-5 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-gray-100 via-gray-900 to-black pointer-events-none" />
        <div className="absolute top-4 right-4 opacity-20 font-serif font-bold text-xl uppercase tracking-widest">
          The Boardroom
        </div>

        {/* 1. THE VERDICT */}
        <motion.div
          initial={{ scale: 0.8, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ type: "spring", bounce: 0.5 }}
          className="mb-8"
        >
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-[0.3em] mb-2">
            Viability Score
          </h2>
          <div
            className={`text-8xl md:text-9xl font-serif font-black ${scoreColor} leading-none tracking-tighter`}
          >
            {roastResult.score}
          </div>
          <div className="mt-2 inline-block px-4 py-1 rounded-full border border-border bg-secondary/50 text-xs font-bold uppercase tracking-wider">
            {roastResult.verdict}
          </div>
        </motion.div>

        {/* 2. THE BURN */}
        <div className="space-y-6 relative z-10">
          <blockquote className="text-xl md:text-2xl font-serif italic leading-relaxed text-foreground">
            "{roastResult.burn}"
          </blockquote>

          <div className="h-px w-24 bg-border mx-auto" />

          <p className="text-muted-foreground text-sm leading-relaxed max-w-lg mx-auto">
            {roastResult.details}
          </p>
        </div>

        {/* Footer for the Image */}
        <div className="mt-12 text-xs text-muted-foreground uppercase tracking-widest opacity-50">
          Generated by AI Boardroom
        </div>
      </div>

      {/* ACTION BUTTONS (Outside the capture area) */}
      <div className="mt-8 flex flex-col md:flex-row gap-4 justify-center">
        <Button
          onClick={downloadImage}
          className="font-serif font-bold tracking-wide"
          variant="outline"
        >
          <Download className="mr-2 h-4 w-4" /> Save Evidence
        </Button>

        <Button
          onClick={resetRoast}
          className="bg-secondary text-secondary-foreground hover:bg-secondary/80 font-serif font-bold tracking-wide"
        >
          <RefreshCw className="mr-2 h-4 w-4" /> Try Another Idea
        </Button>
      </div>
    </div>
  );
};

export default Scorecard;
